### ISSUE TITLE
Fix NNCF Issues.

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#20]
[OpenvinoCallback](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/core/callbacks/compress.py) and [NNCFCallback](https://github.com/openvinotoolkit/anomalib/blob/development/anomalib/core/callbacks/nncf_callback.py) implementations are quite similar. They only differ in terms of type of the quantization.

# Tasks
- [ ] Refactor Compression and NNCF callbacks could be merged into a single callback
- [ ] Design an error handling mechanism to pick up the errors caused by nncf 2.1.0 vs 2.2.0. Warn the user to manually upgrade the nncf to 2.2.0
- [ ] configure openvino and nncf callbacks from the config.yaml file.
- [ ] change the requirements in openvino.txt - `nncf>=2.1.0`
- [ ] Modify the nightly tests to handle nncf tests.
- [ ] Refactor NNCF config.
