### ISSUE TITLE
📋 [TASK] Implement Vision Language Model (VLM) Support

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#2375]
## Problem Statement

Traditional anomaly detection systems often struggle with limited data scenarios and lack the ability to explain their detections. We need to address these challenges by integrating Vision Language Models (VLMs) into anomalib.

## Objective

Implement VLM support in anomalib to enable few-shot and zero-shot anomaly detection with explanatory capabilities.

## Proposed Solution

Create a new `VlmAd` class as a subclass of `AnomalyModule` that leverages various VLM backends for anomaly detection.

## Tasks

1. Design and Implement `VlmAd` class
   - [x] Create `VlmAd` class inheriting from `AnomalyModule`
   - [x] Implement `__init__` method with parameters for backend selection and configuration
   - [ ] Design and implement `validation_step` method for anomaly detection
   - [ ] Implement `learning_type` property to support zero-shot and few-shot learning

2. Implement Backend Support
   - [ ] Create `BackendModels` enum with supported models:
     ```python
     class BackendModels(Enum):
         LLAMA_OLLAMA = "llava"
         GPT_4V = "gpt-4v-vision-preview"
         VICUNA_7B = "llava-hf/llava-v1.6-vicuna-7b-hf"
         VICUNA_13B = "llava-hf/llava-v1.6-vicuna-13b-hf"
         MISTRAL_7B = "llava-hf/llava-v1.6-mistral-7b-hf"
     ```
   - [ ] Implement `Backend` base class
   - [ ] Create specific backend classes (Ollama, ChatGPT, Huggingface) inheriting from `Backend`
   - [ ] Implement `_setup_vlm_backend` method in `VlmAd` to initialize appropriate backend

3. Implement Few-shot Learning Support
   - [ ] Design `collect_reference_images` method for gathering examples
   - [ ] Implement logic to use reference images in prompts

4. Implement Prompts and Parsing
   - [ ] Create `Prompt` class or similar structure for managing prompts
   - [ ] Implement methods for generating prompts based on learning type (zero-shot or few-shot)
   - [ ] Develop response parsing logic to extract anomaly predictions and explanations

5. Error Handling and Logging
   - [ ] Implement comprehensive error handling for API interactions and backend operations
   - [ ] Set up logging system for debugging and monitoring

6. Testing and Validation
   - [ ] Write unit tests for `VlmAd` class and its methods
   - [ ] Implement integration tests with each backend
   - [ ] Test zero-shot and few-shot capabilities on standard datasets (e.g., MVTec AD)

7. Documentation
   - [ ] Write detailed docstrings for `VlmAd` class and its methods
   - [ ] Create usage examples and tutorials
   - [ ] Update anomalib main documentation to include VLM support

### Acceptance Criteria

1. `VlmAd` class is fully implemented and integrated into anomalib
2. All specified backends (LLAMA, GPT-4V, VICUNA, MISTRAL) are supported and functional
3. Zero-shot and few-shot learning modes are implemented and working correctly
4. Anomaly detection results include explanations from the VLM
5. Comprehensive test suite passes for all implemented features
6. Documentation is complete, including class descriptions and usage examples

### Priority

Medium

### Current Status

Ready for Review

### Additional Information

PR Link: https://github.com/openvinotoolkit/anomalib/pull/2344
