### ISSUE TITLE
Dockerize Anomalib CI

### ISSUE THREAD

**Issue by ashwinvaidya17** [openvinotoolkit/anomalib#611]
# Description

- Current CI has a lot of commands that are specific to a single machine. Migrate to a docker based runner

## Subtasks

- [x] Create CI setup readme
- [x] Update dockerfile if necessary
- [x] Update github action if necessary
- [x] Install runner on two macines
